% This code takes sHI generated by a neural network and creates a damage probability map
% based on sensor pairs defined in SP.mat

% You can specify which paths to plot and at which state, additionally an animation (over states) can be created

% Based on the Rapid alghoritm

%% 1. Path Setup (mirror training script essentials)
scriptDir = fileparts(mfilename('fullpath'));
projectRoot = scriptDir; % this file appears at project root
addpath(fullfile(projectRoot,'src','models'));
addpath(fullfile(projectRoot,'src','models/layers'));
addpath(fullfile(projectRoot,'src','data'));
addpath(fullfile(projectRoot,'src','utils'));

reqClasses = { 'change_format','deconcatenation','GAN' };
for c = reqClasses
	pth = which(c{1});
	if isempty(pth)
		error('[HI_plot] Required class "%s" not found on path. Add src/models before loading network.', c{1});
	else
		fprintf('[HI_plot] Found class %s at %s\n', c{1}, pth);
	end
end


close all; 
fprintf('[HI_plot] Starting inference script...\n');

% Use explicit fprintf + input('>') to avoid Live Editor / console '?' issueHI_plot

% fprintf('Enter the model file path:\n');
% modelFile = strtrim(input('> ', 's'));

modelFile= 'C:\Users\Maria\Documents\Honours Programme\Networks\GAN\results\f4_FC_Net_stupid_loss_with_AE\fc_path_28_net_loss_0.011118.mat'; % choose which model to use
convolutional_mode = true; % set to true for convolutional GAN mode, false for FC mode
fprintf('Enter which panel to use\n');
panel_number = str2double(input('> ', 's'));
% fprintf('Is the network using Graph layer? (true/false):\n');
% GAN_mode = input('> ');
GAN_mode = true;
% infer the path_id from the net name
path_id = str2double(regexp(modelFile, 'path_(\d+)_net', 'tokens', 'once'));
% fprintf('Do you want to use one frequency only? (true/false):\n');
% single_freq = input('> ');
single_freq = true;
if single_freq
    % fprintf('Enter the frequency index to extract (1-6):\n');
    % frequencies = str2double(input('> ', 's'));
    frequencies = 4;
else
    frequencies = 1:6; % specify which frequencies to plot (1 to 6)
end

paths_to_plot = path_id;


%% 4. Build Inference Datastore (MiniBatchSize=1, no overlap)
miniBatchSize = 1; overlap = 0;  % numCycles used only for latent formula
AE_net_folder = 'C:\Users\Maria\Documents\Honours Programme\Networks\GAN\results\1p1f_Sparse_Fully_Connected_AE\freq_4\bayesian_optimization';
cacheRoot = fullfile(projectRoot, 'data', 'latent_cache');
if ~exist(cacheRoot,'dir'), mkdir(cacheRoot); end

if single_freq
    
    % FC mode: single path latent per cycle (no spatial dims), CB input format
    rawDs = latent_space_datastore(panel_number, miniBatchSize, overlap, frequencies, false, AE_net_folder, 'path_id', path_id);

else
    error('Only single frequency mode is supported in this script.');
end
numCycles = rawDs.NumObservations;


fprintf('Enter which state to plot (1 to %d):\n', numCycles);
state_to_plot = input('> ');

fprintf('Do you want to create an animation over all states? (true/false):\n');
create_animation = input('> ');

fprintf('Do you want to probe probability at specific points? (true/false):\n');
enable_probe = input('> ');
probePoints = [];
if enable_probe
    fprintf('Use sensor positions as probes? (true/false):\n');
    use_sensors = input('> ');
    % Sensor positions (meters)
    sensor_positions_m = 0.001*[25 25; 
        100 25; 
        140 215; 
        66 215; 
        25 120; 
        140 120; 
        82.5 90; 
        82.5 180];
    if use_sensors
        probePoints = sensor_positions_m;
    else
        fprintf('Enter probe points in millimeters as an Nx2 matrix (e.g., [82.5 120; 50 50]):\n');
        pp_str = input('> ', 's');
        pp_mm = str2num(pp_str); %#ok<ST2NM>
        if isempty(pp_mm) || size(pp_mm,2) ~= 2
            warning('[HI_plot] Invalid probe input. Falling back to sensor positions.');
            probePoints = sensor_positions_m;
        else
            probePoints = 0.001 * pp_mm; % convert mm to meters
        end
    end
end

% Basic validation / defaults
if isempty(modelFile)
    warning('[HI_plot] Empty modelFile. Set a valid path before continuing.');
end

%% 2. Load Trained Network
% Auto-select most recent valid trained GAN model file in results folder
resultsDir = fullfile(projectRoot,'results');
fprintf('[HI_plot] Using model file: %s\n', modelFile);
if ~isfile(modelFile)
    error('[HI_plot] Model file not found: %s', modelFile);
end

if isempty(modelFile)
    error('[HI_plot] No suitable model file containing trained_net found in %s.', resultsDir);
end
% --- Load and display model metadata safely --------------------------------
% Attempt to load model_metadata from the same model file as the network.
metaInfo = whos('-file', modelFile);
hasMeta  = ismember('model_metadata', {metaInfo.name});

if ~hasMeta
    warning('[HI_plot] model_metadata not found in %s. Skipping metadata display.', modelFile);
else
    Smeta = load(modelFile,'model_metadata');
    model_metadata = Smeta.model_metadata;
    if ~isstruct(model_metadata)
        warning('[HI_plot] model_metadata exists but is not a struct (class=%s).', class(model_metadata));
    else
        fprintf('[HI_plot] -------- Model Metadata --------\n');
        flds = fieldnames(model_metadata);
        for f = 1:numel(flds)
            key = flds{f};
            val = model_metadata.(key);
            if isnumeric(val)
                if isscalar(val)
                    fprintf('  %-15s : %g\n', key, val);
                else
                    if isvector(val)
                        fprintf('  %-15s : [%s]\n', key, strtrim(sprintf('%g ', val(:)')));
                    else
                        sz = size(val);
                        fprintf('  %-15s : numeric array size [%s]\n', key, strjoin(string(sz),'x'));
                    end
                end
            elseif isstring(val) || ischar(val)
                fprintf('  %-15s : %s\n', key, string(val));
            elseif isstruct(val)
                fprintf('  %-15s : MSE : %d Monotonicity: %d Proxy : %d\n', key, val.MSE, val.Monotonicity, val.Proxy);
            else
                fprintf('  %-15s : (%s)\n', key, class(val));
            end
        end
        % Explicit important fields (with existence checks)
        impFields = {'timestamp','num_inputs','batch_size','max_epochs','initial_lr', ...
            'optimizer','loss_function','data_cycles','latent_size','final_loss'};
        for k = 1:numel(impFields)
            if ~isfield(model_metadata, impFields{k})
                warning('[HI_plot] Missing expected field: %s', impFields{k});
            end
        end
        fprintf('[HI_plot] --------------------------------\n');
    end
end
if ~isfile(modelFile)
	error('[HI_plot] Model file not found: %s', modelFile);
end

S = load(modelFile, 'trained_net', 'net','finalNet');
if ~isfield(S,'trained_net') 
    if ~isfield(S,'net')
        if ~isfield(S,'finalNet')
            error('[HI_plot] Neither "trained_net" nor "net" nor "finalNet" found in %s', modelFile);
        else
            net=S.finalNet;
        end
    else
        warning('[HI_plot] Using field "net" instead of "trained_net" from %s', modelFile);
        net = S.net;
    end
else
    net = S.trained_net; % dlnetwork expected
end
fprintf('[HI_plot] Loaded network with %d learnables.\n', height(net.Learnables));

%% 3. Inspect Inputs
inNames = net.InputNames; nInputs = numel(inNames);
fprintf('[HI_plot] Network expects %d inputs.\n', nInputs);

% Preallocate latent space buffer
latent_space = zeros(1, rawDs.NumObservations);

for i = 1:rawDs.NumObservations

    % Read one batch to form a prototype; for multi-batch inference loop, reset after each read.
    [batchTbl, info] = read(rawDs); 
    w = width(batchTbl);
    inputCells = cell(1, nInputs);
    if w == (nInputs + 1)
        % Case A: table provides each input as its own column
        for k = 1:nInputs
            raw = batchTbl{1,k};
            % GAN: SCB/SSCB, FC: CB
            
            inputCells{k} = coerceToDlInput(raw, false, 'CB');
            
            sz = size(extractdata(inputCells{k}));
            fprintf('[HI_plot] Input %d -> dlarray size [%s], class=%s\n', k, strjoin(string(sz),'x'), class(extractdata(inputCells{k})));
        end
    elseif w == 2
        % Case B: single input column containing SxC with channels to split
        raw = batchTbl{1,1}; % S x C (or S x S2 x C)
        % If multiple inputs are expected, split along channel dimension
        if nInputs == 1
            
            % FC expects CB only, no spatial dims
            inputCells{1} = coerceToDlInput(raw, false, 'CB');
        
            sz = size(extractdata(inputCells{1}));
            fprintf('[HI_plot] Input 1 -> dlarray size [%s], class=%s\n', strjoin(string(sz),'x'), class(extractdata(inputCells{1})));
        else
            error('[HI_plot] Unexpected single-column table for multiple inputs (nInputs=%d).', nInputs);
        end
    else
        error('[HI_plot] Unexpected table width=%d (expected %d or 2).', w, nInputs+1);
    end
   
    %% 5. Forward Prediction
    try
        nOut = numel(net.OutputNames);
        YPred = cell(1,nOut);
        [YPred{:}] = predict(net, inputCells{:});
    catch ME
        fprintf(2,'[HI_plot][ERROR] Prediction failed: %s\n', ME.message);
        % Extra diagnostics on failure
        for k = 1:numel(inputCells)
            if isa(inputCells{k}, 'dlarray')
                szk = size(extractdata(inputCells{k})); fmts = inputCells{k}.Formats;
                fprintf(2,'[HI_plot][DEBUG] input %d: dlarray size [%s], formats=%s\n', k, strjoin(string(szk),'x'), string(fmts));
            else
                fprintf(2,'[HI_plot][DEBUG] input %d: class=%s\n', k, class(inputCells{k}));
            end
        end
        rethrow(ME);
    end
   
    y = squeeze(extractdata(YPred{1}));
    
    % FC mode: single path latent scalar/vector
    if isvector(y)
        latent_space(1,i) = y(1);
    else
        latent_space(1,i) = y;
    end
    

end

%% 6. Generate Probability Maps for Selected Paths

d103 = 0.001*[50 80]; % position of the inpact for the panel 103
d104 = 0.001*[25 80]; % position of the inpact for the panel 104
d105 = 0.001*[165-50 240-80]; % position of the inpact for the panel 105
d109 = 0.001*[165-82.5 240-100]; % position of the inpact for the panel 109
if panel_number == 103
    demage_point = d103;
elseif panel_number == 104
    demage_point = d104;
elseif panel_number == 105
    demage_point = d105;
elseif panel_number == 109
    demage_point = d109;
else
    demage_point = [0 0];
end
sN = false;
pN = false;
beta = 1.05;
const_clim = true;
enable_ideal_shi = false;
enable_shi_heatmap = true;
enable_shi_lineplot = true;
Wave_velocity = 2*10^2; % m/s
for s = state_to_plot
    sHI_path = latent_space(1, s)';
    probability_map_pairs(paths_to_plot, 'sHI', sHI_path, 'Wave_velocity', Wave_velocity, ...
        'ShowPanel', true, 'CLim', [], 'Plot_demage', demage_point);
end

%% 7. OPTIONAL: Create Animation over All States
ideal_shi = 1 - linspace(0,1,numCycles); % ideal sHI from 1 to 0
if create_animation
    gifFile = fullfile(projectRoot, 'results', sprintf('damage_map_panel_%d_speed_%.1f.gif', panel_number, Wave_velocity));
    delayTime = 1; % seconds
    

    % Initial frame
    s = 1;
    if enable_ideal_shi
        sHI_path = ideal_shi(s);
    else
        sHI_path = latent_space(1, s)';
    end
    
    [P0, xRange, yRange] = probability_map_pairs(paths_to_plot, 'sHI', sHI_path, ...
        'Wave_velocity', Wave_velocity,'NormalizePerPair', pN, 'SumNormalize', sN, 'ShowPanel', false, 'Plot', false);

    disp('Max probability values in initial frame:');
    mP0 = max(P0(:));
    disp(mP0);  
    clim = [0, mP0]; % fix color limits based on first frame
    figure('Name', 'Damage Probability Animation', 'NumberTitle', 'off');
    hImg = imagesc(xRange, yRange, P0);
    set(gca, 'YDir', 'normal');
    if const_clim
        set(gca, 'CLim', clim);
    end
    set(gca, 'XDir', 'reverse');
    axis equal tight;
    colormap(parula);
    colorbar;
    xlabel('x (m)'); ylabel('y (m)');
    title(sprintf('Damage Probability (state %d/%d)', s, numCycles));
    hold on;

    % Overlay panel and sensors
    panel_domain_x = 0.001*[0 0 165 165 0];
    panel_domain_y = 0.001*[0 240 240 0 0];
    positions = 0.001*[25 25; 
        100 25; 
        140 215; 
        65 215; 
        25 120; 
        140 120; 
        82.5 80; 
        82.5 160];
    plot(panel_domain_x, panel_domain_y, 'k-', 'LineWidth', 1.0);
    scatter(positions(:,1), positions(:,2), 25, 'w', 'filled');
    set(gca, 'XDir', 'reverse');
    for i = 1:size(positions,1)
        text(positions(i,1), positions(i,2), num2str(i), 'Color', 'w', 'FontSize',8, 'VerticalAlignment','bottom', 'HorizontalAlignment','right');
    end

    % Plot demage point
    if any(demage_point ~= 0)
        scatter(demage_point(1), demage_point(2), 100, 'r', 'filled', 'DisplayName', 'Damage Point');
        text(demage_point(1), demage_point(2)+0.01, 'Impact', 'Color', 'r', 'FontSize',8, 'VerticalAlignment','bottom', 'HorizontalAlignment','center');
    end

    hold off;

    % Write first frame
    frame = getframe(gcf);
    img = frame2im(frame);
    [A, map] = rgb2ind(img, 256);
    imwrite(A, map, gifFile, 'gif', 'LoopCount', Inf, 'DelayTime', delayTime);

    % Subsequent frames
    for s = 2:numCycles
        if enable_ideal_shi
            sHI_path = ideal_shi(s);
        else
            sHI_path = latent_space(1, s)';
        end
        
        [P, ~, ~] = probability_map_pairs(paths_to_plot, 'sHI', sHI_path, ...
            'Wave_velocity', Wave_velocity,'NormalizePerPair', pN, 'SumNormalize', sN, 'ShowPanel', false, 'Plot', false, 'CLim', []);
        set(hImg, 'CData', P);
        title(sprintf('Damage Probability (state %d/%d)', s, numCycles));
        drawnow;

        frame = getframe(gcf);
        img = frame2im(frame);
        [A, map] = rgb2ind(img, 256);
        imwrite(A, map, gifFile, 'gif', 'WriteMode', 'append', 'DelayTime', delayTime);
    end
end

%% 8. OPTIONAL: Probe probability over states and plot
if enable_probe
    try
        statesVec = 1:numCycles;
        [series, statesVec] = probe_probability_series(latent_space, paths_to_plot, statesVec, probePoints, ...
            'Test', true, 'Beta', 1.3, 'NormalizePerPair', pN, 'SumNormalize', sN);

        figure('Name','Probe Probability vs State','NumberTitle','off');
        plot(statesVec, series');
        grid on;
        xlabel('State'); ylabel('Summed probability at probe');
        title('Probability evolution at probes');
        legend(arrayfun(@(i) sprintf('Probe %d', i), 1:size(series,1), 'UniformOutput', false), 'Location','bestoutside');

        % Save results
        probeFile = fullfile(projectRoot, 'results', sprintf('probe_series_panel_%d.mat', panel_number));
        save(probeFile, 'series', 'statesVec', 'probePoints', 'paths_to_plot', 'panel_number');
        fprintf('[HI_plot] Probe series saved to %s\n', probeFile);
    catch ME
        fprintf(2,'[HI_plot][ERROR] Probe series failed: %s\n', ME.message);
    end
end

if enable_shi_heatmap
    flatent = figure("Name","Latent Space","NumberTitle","off");
    imagesc(latent_space);
    colorbar;
    title(sprintf('Latent Space Over States, for Panel %d', panel_number));
    xlabel('States Index');
    ylabel('Input Index');
end
global_health =sum(latent_space.^2,1);
global_health_plot = figure("Name","Global Health Plot","NumberTitle","off");
hold on;
plot(1:numCycles, global_health, 'DisplayName', 'Global Health');
title('Global Health Over Cycles');
xlabel('Cycle Index');
ylabel('Global Health Value');
hold off;


if enable_shi_lineplot
    RUL = (1:numCycles)/numCycles; % Remaining Useful Life from 1 to 0
    line_flatent = figure("Name","Latent Space Lines","NumberTitle","off");
    hold on;
    
    plot(RUL, latent_space(1,:), 'DisplayName', sprintf('Path %d', path_id));
    
    title('Latent Space Over Cycles - Line Plot');
    xlabel('Cycle Index');
    ylabel('Latent Value');
    legend('show');
    hold off;
end
%% functions
function dlX = coerceToDlInput(x, preferSSCB, fmt)
    if nargin < 2, preferSSCB = false; end
    if nargin < 3 || isempty(fmt), fmt = 'SCB'; end
    % Ensure underlying is numeric and full
    if iscell(x)
        if numel(x) == 1
            x = x{1};
        else
            error('[HI_plot] Invalid cell input with %d elements; expected scalar cell.', numel(x));
        end
    end

    if istable(x)
        error('[HI_plot] Table encountered where numeric array expected.');
    end

    if ~isnumeric(x) && ~islogical(x)
        error('[HI_plot] Input must be numeric/logical, got %s.', class(x));
    end

    if issparse(x)
        x = full(x);
    end

    % Cast to single to match typical training
    if ~isa(x,'single') && ~isa(x,'double') && ~islogical(x)
        x = single(x);
    end

    % Add batch dimension and format based on requested fmt
    switch upper(fmt)
        case 'CB' % channels x batch
            if isvector(x)
                x = reshape(x, [], 1);
            elseif ndims(x) == 2 && size(x,2) ~= 1
                % Assume columns are channels; keep B=1
                x = reshape(x, size(x,1), 1);
            elseif ndims(x) > 2
                x = reshape(x, [], 1);
            end
            dlX = dlarray(x, 'CB');
        case 'SCB'
            nd = ndims(x);
            if nd == 2
                x = reshape(x, size(x,1), size(x,2), 1);
            elseif nd == 1
                x = reshape(x, [], 1, 1);
            elseif nd > 3
                error('[HI_plot] SCB expects up to 2D + batch. Got rank=%d', nd);
            end
            dlX = dlarray(x, 'SCB');
        case 'SSCB'
            if preferSSCB
                if ndims(x) == 2
                    x = reshape(x, size(x,1), size(x,2), 1, 1);
                elseif ndims(x) == 3
                    x = reshape(x, size(x,1), size(x,2), size(x,3), 1);
                end
            else
                if ndims(x) == 2
                    x = reshape(x, size(x,1), size(x,2), 1, 1);
                end
            end
            dlX = dlarray(x, 'SSCB');
        otherwise
            error('[HI_plot] Unsupported format "%s"', fmt);
    end
end

%% Example Input
% C:\Users\Maria\Documents\Honours Programme\Networks\GAN\results\f4_GAN_Net_wls_with_AE\fc_all_path_net_loss_0.203931.mat
% 104
% true
% true
% 4
% [29 ]
% [1 27]
% true
% false
